### ISSUE TITLE
allow persistent delivery option

### ISSUE THREAD

**Issue by peterneorr** [logstash-plugins/logstash-output-stomp#7]
I'd love to see a configuration option to force stomp to send persistent messages.  The stomp documentation states: "By default, Stomp produced messages are set to non-persistent. You have to explicitly tell your Stomp library to add "persistent:true" to all SEND requests, for any messages that you want to persist across ActiveMQ restarts."

I believe the issue and a possible fix is also described here: 
http://stackoverflow.com/questions/29834315/logstash-stomp-activemq

Thanks!

**Comment by consulthys** [comment]
This is now supported since #4 and #8 have been merged.

    stomp {
        host => "localhost"
        port => 61612
        destination => "my_queue"
        headers => {
            "persistent" => true
        }
    }

**Comment by mobimation** [comment]
Is there a recommendation to close the client connection after each message sent and then reconnect just before the next message to send ?
